apiVersion: v1
kind: Pod
metadata:
 name: dbtier-pod
spec:
 containers:
 - name: mysqldb
   image: mysql:5.5
   imagePullPolicy: Never 
   ports:
   - containerPort: 3306
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: awsawsdb
   volumeMounts:
   - name: dbconfig
     mountPath: /etc/mysql/conf.d
 - name: loaddata
   image: sqlclient
   imagePullPolicy: Never 
   volumeMounts:
   - name: myapp
     mountPath: /myapp
 restartPolicy: OnFailure
 volumes:
 - name: dbconfig
   configMap:
     name: dbconfig
 - name: myapp
   hostPath:
     path: /c/Users/mulargui/cluster/healthylinkx-mysql/mysql.init
     type: Directory